apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: kubeapps-repositories-write
rules:
- apiGroups: 
  - kubeapps.com
  resources: 
  - apprepositories
  verbs: 
  - get
  - create
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
